#!/bin/bash -eu

echo '--> generating test plan json'
go run main.go generate

aws s3 sync --acl public-read --sse --delete site s3://nutrack.michaelbruce.co

echo '--> removing test plan json'
rm site/test-plan.json
